version: '3.7'
services:
  mongodb:
    image: mongo:latest
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: xxXX1234
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
